name: Hello World Application  # Every workflow has a name 

# Trigger: It defines how and when your workflow gets run
on:
  push:
    branches: [ master, feature ]
  pull_request:
    branches: [ master, feature ]
  pull_request_review_comment:
    branches: [ master, feature ]
  schedule:
    - cron: '1 * * * *' # runs after every 1 minute

# We can specify a number of jobs. Each job runs on a VM
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run hello-world.py to get the latest data
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: python hello-world.py
          
      - name: commit files
        run: |
          git config --local user.email "arjungoel1995@gmail.com"
          git config --local user.name "Arjun Goel"
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main